- hosts: localhost
  gather_facts: no
  become: true
  vars:
    graylog_fqdn: "localhost"
    graylog_port: "9000"
    graylog_user: "admin"
    graylog_password: "admin"
    graylog_inputs:
      - gelf
      - syslog
      - bal
      - cloudwatch
      - test1


  tasks:
    - name: Display all inputs
      graylog_inputs:
        action: "list"
        protocol: http
        graylog_fqdn: "{{ graylog_fqdn }}"
        graylog_port: "{{ graylog_port }}"
        graylog_user: "{{ graylog_user }}"
        graylog_password: "{{ graylog_password }}"
        validate_certs: "false"
        log_format: "GELF"
        input_protocol: "TCP"
        title: "Test2 input GELF HTTP"
      #loop: "{{ graylog_inputs }}"
      register: input_list

    - name: Print inputs
      ansible.builtin.debug:
        msg: "{{ input_list }}"

    - name: Display all extractors for input
      graylog_inputs:
        action: "list_extractors"
        protocol: http
        graylog_fqdn: "{{ graylog_fqdn }}"
        graylog_port: "{{ graylog_port }}"
        graylog_user: "{{ graylog_user }}"
        graylog_password: "{{ graylog_password }}"
        input_id: "60f096d3062742757d8958c0"
        validate_certs: "false"
        log_format: "GELF"
        input_protocol: "TCP"
        title: "Test2 input GELF HTTP"
      #loop: "{{ graylog_inputs }}"
      register: input_list